[package]
name = "aoc-lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc"
crate-type = ["lib"]

[dependencies]
futures = "0.3.25"
num = "0.4.0"
regex = "1.6.0"

[build-dependencies]
regex = "1.6.0"
