// --- This file was auto-generated by build.rs ---

// Module definitions
pub mod day01_test;
pub mod day02_test;
pub mod day03_test;
pub mod day04_test;
pub mod day05_test;
pub mod day06_test;
pub mod day07_test;
pub mod day08_test;
pub mod day09_test;
pub mod day10_test;
pub mod day11_test;
pub mod day12_test;
pub mod day13_test;
pub mod day14_test;
