[package]
name = "aoc_lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc"
crate-type = ["lib", "cdylib"]

[dependencies]
num = "0.4.0"
regex = "1.6.0"
wasm-bindgen = "0.2"

[build-dependencies]
regex = "1.6.0"
