// --- This file was auto-generated by build.rs ---

// Module definitions
mod day01;

// Re-exports
pub use day01::Day01;

// List of solutions
use crate::solution::{SolutionStatic, SolutionType};
pub fn solution_list() -> Vec<SolutionType> {
    vec![
        Day01::as_type(),
    ]
}
